### ISSUE TITLE
Error: unrecognized arguments for input

### ISSUE THREAD

**Issue by ictoi** [Scarygami/location-history-json-converter#11]
I am getting "error: unrecognized arguments" for input as described here:

http://stackoverflow.com/questions/17118999/python-argparse-unrecognized-arguments

The selected answer works: "If you omit sys.argv then parse_args parses sys.argv as expected."

**Comment by Scarygami** [comment]
Should be fixed with https://github.com/Scarygami/location-history-json-converter/pull/12
