### ISSUE TITLE
Dates should be from UTC epoch time?

### ISSUE THREAD

**Issue by mehrdadn** [Scarygami/location-history-json-converter#14]
Hi,

I noticed you use `datetime.fromtimestamp` to convert epoch timestamps everywhere, but I believe the correct conversion would require `datetime.utcfromtimestamp`? My timestamps all seem to be UTC-based (and I think generally epoch timestamps are).

Thanks!

**Comment by antonio-fiol** [comment]
I made the change from `datetime.fromtimestamp` to `datetime.utcfromtimestamp` in all the appearances in the code, and now my timestamps in the GPX file look right.
