### ISSUE TITLE
TypeError: '>' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by bgunsberger** [Scarygami/location-history-json-converter#26]
Hi,

I get an error trying to run the script on Python 3.6.4:

/ Locations written: 0Traceback (most recent call last):
  File "./location_history_json_converter.py", line 570, in <module>
    sys.exit(main())
  File "./location_history_json_converter.py", line 563, in main
    chronological=args.chronological
  File "./location_history_json_converter.py", line 385, in convert
    if "accuracy" in item and item["accuracy"] > accuracy:
TypeError: '>' not supported between instances of 'int' and 'NoneType'

I've tried with csv and gpx export.

Thanks.

**Comment by torskepostei** [comment]
I get the same error trying to do a KML conversion. 
Some quick googling shows that this may be related to python 2 vs python 3 behaviour, seems to be a bug there related to how the accuracy argument is handled when empty. 
There seems to be a workaround by supplying the accuracy argument when calling location-history-json-converter.

**Comment by dmpop** [comment]
Adding the `-a` parameter works. But it would be really great if this bug is fixed. Please?

**Comment by tomschr** [comment]
From reading the code and the traceback from issue26, I see these problems:

```python
if "accuracy" in item and item["accuracy"] > accuracy:
      continue
```

the variable `item` seems to be a `dict` and returns an `int`. However, by default, `accuracy` is set to `None` as you can see from the function signature:

```python
def convert(locations, output, format="kml",
            js_variable="locationJsonData", separator=",",
            start_date=None, end_date=None, accuracy=None, polygon=None,
            chronological=False):
```

So when calling the `convert` function without setting `accuracy`, it sets the default value which is `None`.
What Python gets is an `int` from `item["accuracy"]` but a `None` from `accuracy`. So you compare `int < None` which doesn't make any sense. :wink: 

**Solution**: You need to set `accuracy` to an integer.

**Comment by tomschr** [comment]
I don't know if this could be useful, but in theory you could simplify the if clause a bit and use the `dict.get()` method:

```python
if item.get("accuracy", 0) >= accuracy:
   continue
```

The docstring for `dict.get()` is:

```
D.get(k[,d]) -> D[k] if k in D, else d.
d defaults to None.
```

This does mean the following:

* If `item` does not have the key `accuracy` it falls back to zero (the default).
* If `item` does have the key `accuracy`, it retrieves the value of that key.

Test it if this could be useful. :wink:

**Comment by mifrey00** [comment]
> I don't know if this could be useful, but in theory you could simplify the if clause a bit and use the `dict.get()` method:
> 
> ```python
> if item.get("accuracy", 0) >= accuracy:
>    continue
> ```

I tried your suggestion but I get the same error with a '>=' now: TypeError: '>=' not supported between instances of 'int' and 'NoneType'

**Comment by tomschr** [comment]
@mifrey00 Thanks for your reply. :+1: 

That was expected. :wink: You forgot to adapt the default of  `accuracy`. Either you change the default value from `None` to `0` (zero) in the function signature, **or** you set it in the function body. 

I don't know the exact semantics of  `accuracy`, but if it makes sense to set the default to zero, the function signature should look like this:

```python
def convert(locations, output, format="kml",
            js_variable="locationJsonData", separator=",",
            start_date=None, end_date=None, accuracy=0, polygon=None,
            chronological=False):
```

If this is not possible for some reason, I would propose the following code:

```python
def convert(locations, output, format="kml",
            js_variable="locationJsonData", separator=",",
            start_date=None, end_date=None, accuracy=None, polygon=None,
            chronological=False):
    # ...
    if accuracy is None:
        accuracy = 0  # set it to a useful "default" integer which allows comparison
    # the rest of the code
```

Either way, the variable `accuracy` has to be an integer **before** the comparison. If you do one of the two methods, the comparison should work again.

**Comment by Scarygami** [comment]
This error is now fixed in the script.
