### ISSUE TITLE
WSL2 - Ubu18.04 - Quick Question

### ISSUE THREAD

**Issue by 1415926535** [Scarygami/location-history-json-converter#28]
I installed python3 in my WSL2 environment to parse my location data. After getting errors I copied your commands from the Medium post and still can't get past 'invalid syntax'. 

`    print("\r%s / Locations written: %s" % (time.strftime("%Y-%m-%d %H:%M"), added), end="")
                                                                                        ^
SyntaxError: invalid syntax`

Is this a WSL2 problem? If so then I'll not bug you anymore.

Python 3.6.9

![image](https://user-images.githubusercontent.com/15851161/80387003-1cdd3900-8876-11ea-8439-30c541fc40e6.png)

**Comment by Scarygami** [comment]
Hi, are you sure the script is executing with Python 3 and not with Python 2?
The print function in the form used is only available in Python 3 and would through a syntax error as you've shown in Python 2

**Comment by 1415926535** [comment]
3.8.2 but it's no longer urgent/important. I'll dabble with it later for fun but probably need to improve my python skills first. Thanks for your work and your time. Cool stuff.
