### ISSUE TITLE
error when using csvfull

### ISSUE THREAD

**Issue by marmaqtcs** [Scarygami/location-history-json-converter#29]
Hi, I'm getting a error (see attached). All the files are in the same folder and I'm running the following command:
'python location_history_json_converter.py 2020_JANUARY.json myshis.csv -f csvfullest'

![fhs error](https://user-images.githubusercontent.com/55256132/81994230-3adbc500-95fc-11ea-8ddb-58272ddeefea.png)

Thanks in advance

**Comment by marmaqtcs** [comment]
update:  using python3 

![py err](https://user-images.githubusercontent.com/55256132/82000377-03c1df80-960d-11ea-9279-f7c4fe1ca75c.png)

**Comment by Scarygami** [comment]
Hi, I wasn't aware that the Takeout data now includes the Semantic Location History. I have looked at those files and I don't see a way at the moment to make them useable with this script. So as @pakair mentioned you have to use the `Location History.json` and not the files in Semantic Location History to use this converter.
