### ISSUE TITLE
startdate and enddate hour offsets

### ISSUE THREAD

**Issue by ChickenSupreme** [Scarygami/location-history-json-converter#30]
I'm using this project to split a very large (i.e. multiple year) file into individual files, one for each calendar day. I wanted to be able to split the days at a time other than 0000 UTC so I made the following changes.

At the top of the python file:

```python
from datetime import timedelta
```

At the bottom of the python file (before the convert call):

```python
    if args.startdate:
        args.startdate = args.startdate + timedelta(hours=7)

    if args.enddate:
        args.enddate = args.enddate + timedelta(hours=7)
```

It seems to work well. Of course it would be better to pass the hour offset on the command line but I haven't coded that part. If you're interested and want me to make a pull request I'd be happy to do so.

**Comment by ChickenSupreme** [comment]
Thanks. I'm new to github but from what I've read I think you need to give me access to be able to create a branch? It may take me a few days to figure it out and get the command line code written but I'll work on it.

**Comment by Scarygami** [comment]
Closed in https://github.com/Scarygami/location-history-json-converter/pull/32
